<%@ Page Title="" Language="C#" MasterPageFile="~/Forms/MasterPage.master" AutoEventWireup="true" CodeFile="Lavori.aspx.cs" Inherits="Forms_Lavori" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %><asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server"></asp:Content><asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">    <div class="container mt-5 ">        <div class="row">            <div class="offset-1 col-lg-11 text-center">                <h3>Gestione Lavori</h3>            </div>        </div>        <div class="row">            <div class="offset-1 col-lg-11 text-center">                <asp:Button ID="btnNuovoLavoro" class="text-center" runat="server" Style="width: 20%; height: 30px; margin-top: 20px;" Text="Inserire nuovo lavoro" />                <asp:Button ID="btnModificaLavoro" class="text-center" runat="server" Style="width: 20%; margin-left: 50px; height: 30px; margin-top: 20px;" Text="Modificare lavoro" />            </div>        </div>        <div class="row mt-4">            <div class="col-lg-11 offset-1" style="overflow: auto">                <asp:GridView ID="grigliaLavori" runat="server" AutoGenerateColumns="False" DataKeyNames="chiave" DataSourceID="sdsGrigliaLavori" OnSelectedIndexChanged="grigliaLavori_SelectedIndexChanged">
                    <Columns>
                        <asp:CommandField ShowSelectButton="True" />
                        <asp:BoundField DataField="chiave" HeaderText="chiave" InsertVisible="False" ReadOnly="True" SortExpression="chiave" Visible="False" />
                        <asp:BoundField DataField="DATAORA" HeaderText="DATAORA" SortExpression="DATAORA" />
                        <asp:BoundField DataField="ORE" HeaderText="ORE" SortExpression="ORE" />
                        <asp:BoundField DataField="DESCRIZIONE" HeaderText="DESCRIZIONE" SortExpression="DESCRIZIONE" />
                        <asp:BoundField DataField="PERNOTTAMENTO" HeaderText="PERNOTTAMENTO" SortExpression="PERNOTTAMENTO" />
                        <asp:BoundField DataField="PASTO" HeaderText="PASTO" SortExpression="PASTO" />
                        <asp:BoundField DataField="KM" HeaderText="KM" SortExpression="KM" />
                        <asp:BoundField DataField="PEDAGGI" HeaderText="PEDAGGI" SortExpression="PEDAGGI" />
                        <asp:BoundField DataField="MEZZI" HeaderText="MEZZI" SortExpression="MEZZI" />
                        <asp:BoundField DataField="SPESEEXTRA" HeaderText="SPESEEXTRA" SortExpression="SPESEEXTRA" />
                        <asp:BoundField DataField="DESCRIZIONESPESEEXTRA" HeaderText="DESCRIZIONESPESEEXTRA" SortExpression="DESCRIZIONESPESEEXTRA" />
                        <asp:CheckBoxField DataField="ACCETTAZIONESPESE" HeaderText="ACCETTAZIONESPESE" SortExpression="ACCETTAZIONESPESE" />
                    </Columns>
                    <SelectedRowStyle  BackColor="LightBlue"/>
                </asp:GridView>
                <asp:SqlDataSource ID="sdsGrigliaLavori" runat="server" ConnectionString="<%$ ConnectionStrings:AGAMENNONEConnectionString %>" SelectCommand="LAVORI_SelectAll" SelectCommandType="StoredProcedure"></asp:SqlDataSource>            </div>        </div>    </div>    <asp:ScriptManager ID="ScriptManager1" runat="server">    </asp:ScriptManager>    <%-- pulsante che apre il popup --%>    <%-- chiamata del popup --%>    <cc1:ModalPopupExtender ID="mp1" runat="server" PopupControlID="Panl1" TargetControlID="btnNuovoLavoro"        CancelControlID="btnChiudiPopup" BackgroundCssClass="Background">    </cc1:ModalPopupExtender>    <%-- contenuto del popup --%>    <asp:Panel        ID="Panl1"        runat="server"        CssClass="Popup"        align="center"        Style="display: none">        <%--l'iframe è un contenitore che ha la possibilità di richiamare una pagina--%>        <iframe style="width: 98%; height: 388px;" id="Iframe2" src="/Forms/LAVORI/InserisciLavoro.aspx" runat="server"></iframe>        <br />        <asp:Button ID="btnChiudiPopup" Style="width: 30%; height: 30px;" runat="server" Text="Chiudi" OnClick="btnChiudiPopup_Click" />        <%--chiude il popup--%>    </asp:Panel>    <%-- pulsante che apre il popup --%>    <%-- chiamata del popup --%>    <cc1:ModalPopupExtender ID="ModalPopupExtender1" runat="server" PopupControlID="Panel1" TargetControlID="btnModificaLavoro"        CancelControlID="btnChiudiPopup" BackgroundCssClass="Background" Enabled="false">    </cc1:ModalPopupExtender>    <%-- contenuto del popup --%>    <asp:Panel        ID="Panel1"        runat="server"        CssClass="Popup"        align="center"        Style="display: none">        <%--l'iframe è un contenitore che ha la possibilità di richiamare una pagina--%>        <iframe style="width: 98%; height: 388px;" id="Iframe1" src="/Forms/LAVORI/ModificaLavoro.aspx" runat="server"></iframe>        <br />        <asp:Button ID="Button2" class="text-center" Style="width: 30%; height: 30px;" runat="server" Text="Chiudi" OnClick="btnChiudiPopup_Click" />        <%--chiude il popup--%>    </asp:Panel></asp:Content>

